### ISSUE TITLE
GraphiQL Working Group/ GraphiQL 1.0 invite

### ISSUE THREAD

**Issue by acao** [OneGraph/graphiql-explorer#12]
Hey folks!

The GraphQL working group met last week, and we are going to convene a new GraphiQL Working Group! Towards a 1.0, please join us if you can!

https://github.com/graphql/graphql-wg/issues/136

**Comment by sgrove** [comment]
This would be great, would love to join! Thank you for the heads up.

Is there a date/time set already?

**Comment by acao** [comment]
not yet, I'll report back once it's been set, just wanted to put it on your radar for now. that graphql-wg issue is probably where we will schedule it! looking forward to collaborating
