### ISSUE TITLE
Integrating with Gatsby?

### ISSUE THREAD

**Issue by AniaMakes** [OneGraph/graphiql-explorer#15]
I am currently using Gatsby and was dismayed to realise that their GraphiQL doesn't have the explorer feature (I used postgraphile in one of my previous projects and it was amazing having it). 

I had a quick look but I have no idea where to even start if I were to make a PR with Gatsby to do that myself...

Many thanks for your time and work.

**Comment by sgrove** [comment]
Great news, thanks to folks working hard on the Gatsby side of things, it's on its way! https://github.com/gatsbyjs/gatsby/pull/14280#pullrequestreview-241474771

**Comment by lannonbr** [comment]
And it now has been merged in as of Gatsby 2.7.3. This issue can be closed.

**Comment by sgrove** [comment]
Thanks for the heads up @lannonbr!
