### ISSUE TITLE
Delete query from explorer

### ISSUE THREAD

**Issue by deadcoder0904** [OneGraph/graphiql-explorer#18]
Currently, we have to delete query from the editor but it would be nice if it's one click (&times;) in explorer to remove unused queries.

**Comment by FluorescentHallucinogen** [comment]
@deadcoder0904 PTAL at https://github.com/OneGraph/graphiql-explorer/issues/10#issuecomment-491529125. :wink:

**Comment by sgrove** [comment]
I agree, this would be nice to add!

**Comment by FluorescentHallucinogen** [comment]
This issue can be closed as fixed by #44.
