### ISSUE TITLE
Add graphql version 14 into peer deps to avoid `has incorrect peer dependency` warning

### ISSUE THREAD

**Issue by jvega190** [OneGraph/graphiql-explorer#23]
Hi, I'm using the graphiql-explorer with graphql version 14 and it all works fine, but when building, or installing deps, it shows a warning saying `@graphiql-explorer@0.4.3 has incorrect peer dependency...`. So if it newer versions are added into peerDependencies then warning will go away. I can also send a PR if needed. 

Thanks

**Comment by alanpoulain** [comment]
The PR already exists: https://github.com/OneGraph/graphiql-explorer/pull/16.

**Comment by jvega190** [comment]
That's great, thanks!
