### ISSUE TITLE
Host GraphiQL+Explorer where users can enter any endpoint URL

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [OneGraph/graphiql-explorer#5]
In https://www.onegraph.com/graphiql it's not possible to change endpoint URL to any other.

Could you please host GraphiQL+Explorer where users can enter any endpoint URL like in:

https://lucasconstantino.github.io/graphiql-online/

https://www.graphqlbin.com/

https://altair-gql.sirmuel.design/

**Comment by FluorescentHallucinogen** [comment]
@dwwoelfel @sgrove @rofrischmann PTAL.

**Comment by sgrove** [comment]
@FluorescentHallucinogen The goal right now is to upstream this + some other plugins into GraphiQL proper, so that changing the URL/headers is a simple plugin. Then hosting a static GraphiQL instance somewhere would be trivial for people.

**Comment by FluorescentHallucinogen** [comment]
Closed in favor of https://graphiql-online.com (https://github.com/hasura/graphql-engine/tree/master/community/tools/graphiql-online).

See more info here: https://dev.to/hasurahq/hasura-explorer-feature-as-part-of-the-console-or-stand-alone-14ie
