### ISSUE TITLE
Integrate Explorer into Apollo Client DevTools

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [OneGraph/graphiql-explorer#6]
Since [Apollo Client DevTools](https://github.com/apollographql/apollo-client-devtools) contains GraphiQL, integrate the Explorer into it will be easy.

**Comment by sgrove** [comment]
@FluorescentHallucinogen That's a great idea! Thanks for the suggestion.

I'll reach out to them to see if they'd be up to have the integration.

**Comment by FluorescentHallucinogen** [comment]
@sgrove Any news?

**Comment by sgrove** [comment]
Indeed! Watch this space ;)

**Comment by sgrove** [comment]
Update, upstream PR is here https://github.com/apollographql/apollo-client-devtools/pull/199/files

**Comment by sgrove** [comment]
Still tracking the upstream issue 😂

**Comment by RIP21** [comment]
@sgrove BTW. It's there, but if you have long list of queries/mutations whatever available it's without a scroll.
Take a look.
https://github.com/apollographql/apollo-client-devtools/issues/214

**Comment by FluorescentHallucinogen** [comment]
Closed as solved. 🎉

**Comment by deligent-ant** [comment]
> Since [Apollo Client DevTools](https://github.com/apollographql/apollo-client-devtools) contains GraphiQL, integrate the Explorer into it will be easy.

can you help me,give me a demo about how to combine exploree with graphiql in apollo
