### ISSUE TITLE
Integer arguments get converted into strings

### ISSUE THREAD

**Issue by sgrove** [OneGraph/graphiql-explorer#8]
Try this query in [OneGraphiQL](https://serve.onegraph.com/short/27X26D):
```
{
  gitHub {
    user(login: "sgrove") {
      repositories(first: 10) {
        nodes {
          name
          issues(
            orderBy: { direction: DESC, field: CREATED_AT }
            first: 0
          ) {
            nodes {
              title
            }
          }
        }
      }
    }
  }
}
```

If you update either of the integer arguments in the explorer, they'll be converted into strings in the query document (which will be an invalid query)

**Comment by dwwoelfel** [comment]
Fixed by https://github.com/OneGraph/graphiql-explorer/commit/904f904c79841f1c5c183000489cfc24c1146a58

Please upgrade to v0.3.7 to get the fix.
